#!/bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin:~/.rbenv/bin:~/.rbenv/shims

# move to project root directory
NAME=unicorn
ENVIROMENT=production

SCRIPT_DIR=`dirname $0`
ROOT_DIR=$(cd "${SCRIPT_DIR}/../../"; pwd)

PID="${ROOT_DIR}/tmp/pids/unicorn.pid"
CONF="${ROOT_DIR}/config/unicorn/release.rb"

start()
{
    cd $ROOT_DIR
    if [ -e $PID ]; then
        echo "$NAME already started";
        exit 1;
    fi
    echo "start $NAME";
    bundle exec unicorn_rails -c ${CONF} -E ${ENVIROMENT} -D
}

stop()
{
    if [ ! -e $PID ]; then
        echo "$NAME not started";
        exit 1;
    fi
    echo "stop $NAME";
    kill `cat ${PID}`
    rm -f $PID
}

graceful_stop()
{
    if [ ! -e $PID ]; then
        echo "$NAME not started";
        exit 1;
    fi
    echo "stop $NAME";
    kill -QUIT `cat ${PID}`
    rm -f $PID
}

reload()
{
    if [ ! -e $PID ]; then
        echo "$NAME not started";
        start
        exit 0;
    fi
    echo "reload $NAME";
    kill -USR2 `cat ${PID}`
}

restart()
{
    if [ ! -e $PID ]; then
        echo "$NAME not started";
        start
        exit 0;
    fi
    echo "restart $NAME";
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    graceful_stop)
        graceful_stop
        ;;
    reload)
        restart
        ;;
    restart)
        restart
        ;;
    *)
        echo "Syntax Error: release [start|stop|graceful_stop|reload|restart]"
        ;;
esac
